### ISSUE TITLE
Ну типа, всё ещё игра вылетает при запуске

### ISSUE THREAD

**Issue by MurzikViskas** [ark120202/angel-arena-black-star#110]
Весьма большая проблема отпугивающая огромное кол-во людей. Невозможно прогрузится. Приходится перезаходить, но люди не могут нормально перезайти - сливают на этом ммр и калибровку. Желателен нерф, как можно быстрее. Я бы ещё предложил сбросить ммр после этого - но на Ваше усмотрение.

**Comment by ark120202** [comment]
Не смог повторить с >5 перезапусков, нужно больше деталей

**Comment by ark120202** [comment]
Could be fixed in cf15255e870f45db51d65a57dd7da27f1ed06a4e

**Comment by ark120202** [comment]
Appears to be solved.
