### ISSUE TITLE
Нерф гирокоптера

### ISSUE THREAD

**Issue by MurzikViskas** [ark120202/angel-arena-black-star#112]
Гирыча нужно чинить. Простые варианты -
1) Раскидать таланты по дереву(сбились, и теперь талант 60 уровня можно прокачать на 10)
2) Отключить работу лука на гирыче, поскольку на каждую тычку с флак кеннон - работает  лук.

**Comment by cmdorexe** [comment]
Думаю лучше отключить Флак когда в инвентаре лук.

**Comment by ark120202** [comment]
Fixed in ebb905cb4f7d8e6de00045f496564958b3949a14
