### ISSUE TITLE
make more propotional gold grow to kills in streak grow

### ISSUE THREAD

**Issue by shimaosu** [ark120202/angel-arena-black-star#114]
for 5-kills streak you get 3000 gold, and for 6-kills streak you get 7000 gold.

**Comment by Alastor029711** [comment]
@ark120202 nooo,  /cc https://vk.com/m.viskas your fucking balance kills streak

**Comment by ark120202** [comment]
@MurzikViskas

**Comment by ark120202** [comment]
Probably won't be done.
