### ISSUE TITLE
Предложение. Предметы

### ISSUE THREAD

**Issue by Heiwen34** [ark120202/angel-arena-black-star#119]
В игре имеется Mjolnir и Maelstorm.
Предлагаю сделать линейку предметов, основанном на Maelstorm.
1. Maelstorm + MKB + рецепт = Maelztorm 1
Новый предмет получает те же, суммированные, характеристики, кроме шанса срабатывания и урона.
Шанс срабатывания молнии станет 24%
Урон молнии 160.
2. Maelstorm 1 + Sang & Yasha + Dark sword + Discord + рецепт = Maelstorm 2
Новый предмет получает те же, суммированные, характеристики, кроме шанса срабатывания и урона., а так же дополнительный эффект
Шанс срабатывания молнии станет 29%
Урон молнии 240
Доп эффект - снижение магического сопротивления на 15%.

**Comment by Alastor029711** [comment]
нет
