### ISSUE TITLE
Проблема героев:

### ISSUE THREAD

**Issue by MurzikViskas** [ark120202/angel-arena-black-star#121]
Рикимару - ульта сломана, миллион атак позволяют быстро фармить, и быстро убивать врагов. Достаточно снизить скорость атаки в ульте.

Гирокоптер - отключить лук, если это ещё не сделано.

**Comment by ark120202** [comment]
Riki fixed in 6e0e7ad95c2c882398e680adebea3c39bda4b181

**Comment by Alastor029711** [comment]
о герокоптере было написано ранее
