### ISSUE TITLE
Пиедложения: Skeleton King, Королева Мечей

### ISSUE THREAD

**Issue by Heiwen34** [ark120202/angel-arena-black-star#142]
Предлагаю заменить умение SK - криты, на обычный призыв скелетов, взяв его у королевы мечей.
А призыв королевы мечей заменить на моба поддержки, который увеличивает скорость атаки, а ульт призывает моба с аурой на увеличение урона. Аганим будет улучшать оба умения. 
Заменить анимацию подкопа, на прыжок Рики, с тем же эффектом стана и добавить радиус в 150 распространения эффекта (по возможности)
Эти изменения, будут более соответствовать героям, нежели чем сейчас. Королевна перейдёт из статуса посредственного дд, в хорошего, а главное ещё и дамажного, семи-сапорта.

**Comment by shimaosu** [comment]
что такое анимация подкопа? +королева вполне играбельный ганг герой, менять его в сторону сапорта нет смысла

**Comment by Heiwen34** [comment]
У Sand King на первом умении используется анимация подкопа :/

Для карты WC3 из героя получается далеко не сильный герой ганга, но как сапорт довольно не плохой.

**Comment by ark120202** [comment]
WK's cirts are no longer that strong on war3, because of latest Dota patch.
Ability changes should be discussed with @Alastor029711 or @MurzikViskas.
