### ISSUE TITLE
Certain issues and suggestions

### ISSUE THREAD

**Issue by shiromizakana** [ark120202/angel-arena-black-star#156]
- [ ]  Open shop hotkey does not work.
- [ ]  Netherdrake boss is not present in 5v5. So fountain camping is not possible in 5v5?
- [ ]  Buy stackable item why having the same item in current selected unit result in the red error message, and said item dropped at base. E.g attribute shards/exp tomes.
- [ ]  Sange and Yasha and Kaya: Sange and Yasha is not coded (?) as part of the SnYnK, thus when you buy SnY, quick buy does not show that you only need to buy Kaya only to complete SnYnK.
- [ ]  Ultimate Scepter does not show the upgraded effect in item description. You need to buy ultimate scepter or its upgrades to know the effect.
- [ ]  Wisp/IO Ultimate: If you take the -60s Relocate Talent, then the cooldown of Relocate in latter level becomes negative. This would result in IO being able to relocate (with teammates) out of duel.
**Easy reproduce**: 
- Duel time is less than 12s.
- Use Relocate so that the return position is not in duel.
- As duel time approaching (<1-2s), spam Relocate (outside of duel area) so as they will proc when IO are in duel. Usually 2-3 Relocate(s) will break the duel restriction, and IO is able to relocate out of duel area.
- As first relocate expiring, since the duel restriction is broken on IO, IO is now teleported back to the original location. IO now can go farm creeps/bosses with no fear of being thrown back into the duel.
- Or worse, IO can tether with ally(ies) and help them out of duel as well.
- The other team may never win the duel.
- [ ]  Ember Spirit's Sleight of Fist: same as IO Ultimate above. He can skip the duel by using Sleight of Fist on big stacks of creeps, so as it still procs when duel approach. When SoF is done, he is at the original position (not in duel).

**Balance Suggestions (mostly for war3 map)**
- [ ] Wraith King's Mortal Strike: 
**Suggestions**
- Remove the instant creep kill effect, as in vanilla Dota.
- Tweak the effect so it does not work on jungle creep.
- Tweak the effect so it does not work on illusion.
- Tweak the effect so it does not proc on all types of critical sources (Crytalis, Daedalus etc.)

- [ ]  Shinobu's Kokorowatari:
**Suggestions**
- Reduce the instant creep kill percentage (down to 1% ?).

- [ ]  Meepo: Meepo can farm the fastest at latter stages with his clones, which would be almost uncounterable.
**Suggestions**
- Reduce gold income/exp from clones (down to 20% ?)

**Comment by ark120202** [comment]
> Open shop hotkey does not work.

It works, but always bound to default keys (F4). Although I have heard that it may not work at all under certain configurations, but it should be Valve's issue.

> Netherdrake boss is not present in 5v5. So fountain camping is not possible in 5v5?

Yes, not possible ATM. AFAIK @savdim99 not wants to add Netherdrake to 5v5 map.

> Buy stackable item why having the same item in current selected unit result in the red error message, and said item dropped at base. E.g attribute shards/exp tomes.

As said in error message, currently there is no method to add stackable item directly to unit's stash.

> Sange and Yasha and Kaya: Sange and Yasha is not coded (?) as part of the SnYnK, thus when you buy SnY, quick buy does not show that you only need to buy Kaya only to complete SnYnK.

It's a quick buy issue. Since shop is rewritten it's possible to detect that, but that would require a lot of logic changes. Maybe I'll implement it after #115.

> Ultimate Scepter does not show the upgraded effect in item description. You need to buy ultimate scepter or its upgrades to know the effect.

Since our scepter is rewritten there's no easy way to do it, but should be possible with some hacks. Moved to #157.

> Wisp/IO Ultimate: If you take the -60s Relocate Talent, then the cooldown of Relocate in latter level becomes negative. This would result in IO being able to relocate (with teammates) out of duel.

> Ember Spirit's Sleight of Fist: same as IO Ultimate above. He can skip the duel by using Sleight of Fist on big stacks of creeps, so as it still procs when duel approach. When SoF is done, he is at the original position (not in duel).

IO's ultimate CD has been nerfed in #154. All issues with duel dodge - in 30592f5fabb497d3defa3cffe9529dbea5a62608.

> Wraith King's Mortal Strike:

Instant creep kill chance was removed in latest dota patch.

> Shinobu's Kokorowatari:

> Meepo: Meepo can farm the fastest at latter stages with his clones, which would be almost uncounterable.

@Alastor029711, but balance suggestions probably would be ignored.
