### ISSUE TITLE
Meepo Bug

### ISSUE THREAD

**Issue by shiromizakana** [ark120202/angel-arena-black-star#158]
Mode: 3v3 (war3_ranked map) with bugged additional faction.
Radiant: Doppelganger (D)
Dire: Meepo (M)
D copies M and play as Meepo with no issue whatsoever. D max-level ulti and gets a total of 4 Meepos, which shows on the left side of the screen. M max-level ulti as well.
D uses Flag to switch faction to Dire. Now there are only two Meepo icons of left side of screen, but the total number of Meepos of D is now 5.
3 Meepos are tied with the primary: attributes increased with shard, dies when primary died.
2 Meepos are separated: attributes are freezed as before using Flag, does not die when primary died.
Randomly (?) all Meepoes are tp back to base.

Further use of Flag (change faction) results in additional separated Meepos spawn (6, 7 etc.).

**Comment by ark120202** [comment]
I think that can be simplified to simple usage of Traitor's Flag on Meepo with maxed ultimate.
