### ISSUE TITLE
Fountain Defense Bug

### ISSUE THREAD

**Issue by AlexFack** [ark120202/angel-arena-black-star#216]
Фонтан не всегда отключается после убийства мидового босса

**Comment by Celireor** [comment]
replay? fountain still do damage after boss dies

(try again with high str saitama)

**Comment by AlexFack** [comment]
Иногда он продолжает ваншотить после убийства босса. Если очень нужен реплей, то вот
3981251051
3978115878
3977948461
В каком-то из них точно видно

**Comment by ark120202** [comment]
07a33ae52005c0bc8d999c5586667e52b05f93a0
