### ISSUE TITLE
Void Talent 

### ISSUE THREAD

**Issue by AlexFack** [ark120202/angel-arena-black-star#217]
Талант на 25% универсального уклонения невозможно прокачать

**Comment by ark120202** [comment]
https://github.com/ark120202/angel-arena-black-star/blob/80cf57a611ae5350a7e3b24d9b1fb29715717b97/game/scripts/vscripts/modules/custom_talents/data.lua#L981
@shimaosu

**Comment by AlexFack** [comment]
![29](https://user-images.githubusercontent.com/29777149/42135242-dfc3c976-7d50-11e8-8fe0-c6747dcb2e05.png)

**Comment by ark120202** [comment]
80cf57a611ae5350a7e3b24d9b1fb29715717b97
