### ISSUE TITLE
Unstable Quasar Bug

### ISSUE THREAD

**Issue by AlexFack** [ark120202/angel-arena-black-star#222]
Предмет позволяет видеть Сларка в ультимейте

**Comment by shimaosu** [comment]
Работает ли с Cursed Eye, или только с квазаром?

**Comment by AlexFack** [comment]
Только с квазаром

**Comment by Celireor** [comment]
https://github.com/ark120202/angel-arena-black-star/pull/233

**Comment by Celireor** [comment]
https://github.com/ark120202/angel-arena-black-star/pull/234
