### ISSUE TITLE
Абуз времени в игре, затягивание

### ISSUE THREAD

**Issue by MurzikViskas** [ark120202/angel-arena-black-star#250]
Сделать чтоб когда тебя убивает "за картой", начисляло фраг за убийство. Аргументация - люди уходят в лвл до 600, и ресаются по 2 минуты, затягивая игру чтоб им не сняло ммр.

**Comment by shimaosu** [comment]
К этому же относится:

Бег на фонтане на карте 1х1 где он не отключается.

Боссы не видят в смоках, что позволяет прятаться от врагов.

Закрывание персонажа между текстурами блинком

**Comment by KaapaTeelb** [comment]
Мб по-пидорски конечно, но, начислять очки каждые условные секунд 10-30 если все из вражеской команды мертвы?
