### ISSUE TITLE
map request

### ISSUE THREAD

**Issue by theraw** [ark120202/angel-arena-black-star#294]
hi
i would like to do a map request, same as WAR3/ranked

But with a big wall in the middle of it which doesn't allow teams to attack each other and they're allowed to fight only in the stage where is meant to fight because some ppl just take a support like IO someone gets troll or legion and spams increases levels faster and goes attack the other team ruining whole game and players are forced to leave what else they can do? just dying can't move from base.
if you think this is a good idea and will do this also i suggest to not leave Freya and that other one (forgot name) in same place leave one in one part another one in other part and make them be random not always the same so even if one team is very good and can kill them faster at last they will not be able to take both those but just one.

i think is a good idea, i mean i get really upset when i play for like 20-30 min then someone comes kills all and most of team leaves and i leave too, so for some ppl makes this mod waste of time. maybe you will say go learn in unraked ok but can you really learn in unraked when medusa takes 3 place of creeps at same time and ends the game all alone in 20 min?

Also i have a question about Faceless void +25% Backtrack can't enable it why?

Thank you.

**Comment by KaapaTeelb** [comment]
Thats quite a point of a game. Thats Angel Arena. You can fight, you can farm, you can gang. Its not restricted

And about bosses. Could be really cool if bosses used their abilities. Would be harder.

**Comment by theraw** [comment]
that's the point of losing players who play this mod. starting from me. if you want to gank fight and farm why did they created a fight stage?! seems useless because 90% of kills is done outside of that.
Also i'm suggesting just a map not making whole mod like this. 
This mod is not like normal dota queue there are players with 7K mmr who come and make like pro with me which i have just 3K mmr, so it doesn't work in the same way of normal dota queue there is no rank matching or something close. so pros can make like pro with new players and new players can just feed.
i was playing right now and was someone with 7K mmr. 20min game after that was totally GG he ruined whole game even freya wasn't able to stop him. where is the fun or gameplay experience here just watching yourself die and die or leave?
if you play this mod a lot i'm sure you've seen players leaving because of this reason!

And we can also spam easy af, how to kill freya in 15m game, take lvl up shards go lvl 400, hit freya make it come close to goblin then attack goblin so freya gets cleave dmg Done. This shouldn't happen.

and if bosses used their abilities i don't think someone will be able to kill them smth can happen only if all 6 have 50x each shard and attack at same time.

if there is a map as i said there will not be gank, but i'm sure that it will keep players more into it playing even if a player increases lvl faster and is good the other player have a chance to comeback and be in same range to do a real fight. but if this map isn't, That 'good' player see that he can kill you easly and will start killing and killing and you decide to see yourself die or leave.

Just i want to know what you do when someone starts to kill you as i said? do you leave or watch yourself die?

And if you say that the point of this mod is who increases his lvl faster and ruins the game, then i'm sorry i've misunderstood the idea of this so this issue can be closed. But as there are created some weird shards i don't think this mod is meant to be for a short fight.

Writed a lot and i'm sorry but i tried to explain that i really like this mod but in the way how it is now i just feel bored with it when a good player is on my team we're free to farm but that farm will be just a waste of time because that good player ends the game alone, if a good player is in other team you have to sit and watch yourself dying like creep.

**Comment by Celireor** [comment]
It won't solve the problem because people would just kill you in duel anyway

**Comment by theraw** [comment]
you are wrong. 
The problem is with some heroes shards doesn't work the same, as i've seen
use a 500 strength shard on sven gives strength and damage 500.
use a 500 strength shard on phantom assassin it gives only strength no damage

So some players choose to get damage first then strength or strength first then damage so in one way you will lose but if you have time to farm you have a chance to win because you can build both strength and damage.

**Comment by ark120202** [comment]
We're actually work on a map with the same concept. It would be released in v2.0.0.

> Also i have a question about Faceless void +25% Backtrack can't enable it why?

It had incorrect level group. Already fixed in develop branch.

**Comment by theraw** [comment]
Thank you
