### ISSUE TITLE
Skeleton King's Ultimate

### ISSUE THREAD

**Issue by iliiliiliili** [ark120202/angel-arena-black-star#3]
Skeleton King's Ultimate is not working often. There are 2 behaviours:
1. You just die, ultimate is not on cooldown after death.
2. You die and respawn but not as usual, you are just a "ghost" – you have no body and can't controll yourself, respawn timer ticks like you are dead and you can take AOE damage.

Mys usual items in late-game: blademail2, max desolator, refresher orb, battle fury, hex edge, aghanim
Ultimate was warking in around 30% cases when I played against Spectre.

**Comment by ark120202** [comment]
Resolved by bfd225f77b0242ee5392fef9fe7d821ec8dd17dd
