### ISSUE TITLE
Отключение фонтана после убийства мид босса

### ISSUE THREAD

**Issue by Alastor029711** [ark120202/angel-arena-black-star#40]
Откючением фонтана после мидд босса поможет быстрее закончить игру не тянуть еще,  ведь если 1 комманда полностью доминирует вы и так проиграете а если не так все плохо то и фонтан вам ненужен

**Comment by masfree** [comment]
@Alastor029711 
Тогда уж у обеих команд.
И спавн перенести в неуязвимую зону с таймером на выселение и несколькими порталами.
Иначе игроки просто бросят играть.

**Comment by Alastor029711** [comment]
@masfree  Мид босса можно убить на 25 минуте если ты выигрываешь против каких либо фидеров скажем так, а если при более адекватной игре то на 30 минуте а если при равной то мидд босса вообще не убивают чаще всего

**Comment by masfree** [comment]
@Alastor029711 могут просто прозевать боса ну или проиграть тимфайт. Сам бос не дает феерического преимущества и его могут просто отдать, обменяв на другие перспективные объекты.А в ситуации с отключением фонтана мета сдвинится к одной цели : убить этого чертового боса.. Тут много спорных ситуаций, но все же затягивать игры по часу по полтора из-за того, что враги просто сидят под фонтаном вообще не хорошо и с этим надо, что-то делать.

**Comment by masfree** [comment]
@Alastor029711 пока спасает палка для телепортации противника и глубокий лейт...
