### ISSUE TITLE
Battle Fury creep damage bonus stacks, is not counted in cleave

### ISSUE THREAD

**Issue by Celireor** [ark120202/angel-arena-black-star#425]
In normal Dota, BF creep damage is affected by cleaves and crits

**Comment by ark120202** [comment]
Actually, we have already discussed it with @MurzikViskas before. I agree that it's inconsistent and unintuitive for most players, but simply including it now would make it too powerful. Maybe it would work if bonus damage would be reduced.

/cc @MurzikViskas

**Comment by Celireor** [comment]
but why does it stack
