### ISSUE TITLE
Notes for future item makers

### ISSUE THREAD

**Issue by Celireor** [ark120202/angel-arena-black-star#434]
Don't put GetAbility, GetSpecialValueFor or GetAbilitySpecial in any function in any applied buff (not directly tied to item via GetIntrinsicModifierName, but an aura or active effect or proc) but OnCreated or if you really need to pass in ability. If you put it in any other function, it will break when someone drop and kill the item.

Instead, try to save all values in OnCreated.

**Comment by ark120202** [comment]
There are already some [utility functions](https://github.com/ark120202/angel-arena-black-star/search?q=StoreAbilitySpecials&unscoped_q=StoreAbilitySpecials) to do it. However, I don't think it worth it in most of the cases, as it generally doesn't affect gameplay. Though it would be nice to work in such edge cases and also it would make sense to follow dota's behavior on not updating modifier variables if it wasn't reapplied, the maintenance cost in it's current form appears too big for me. For 2.0 I plan to have a different way to declare lua abilities and modifiers, which hopefully could abstract this stuff away. Thanks for all these PRs, but for now I think we can leave open only these which affect gameplay and not just hide error messages in the console (they also should be modified to use `StoreAbilitySpecials`).

For the future: it's fine to modify related stuff in a single PR. Before merging I can rebase it, so the result would be the same.
