### ISSUE TITLE
Стегиус

### ISSUE THREAD

**Issue by AlexFack** [ark120202/angel-arena-black-star#63]
Аура Стегиуса работает на иллюзиях (стакается крч).

**Comment by Alastor029711** [comment]
не могу сказать что это сильно имбалансно в плане урона по героям, но в плане босса, ощущается любой минус армор, да может быть так небыло задуманно, что бы на иллюзия работало ульта, но сейчас это работает как фишка, ведь ульта стегиуса накладываеться не 100% а с шансом 15%, а если говорить о снижению армора по боссам, то есть такие герои как алхимик слардар сф и некоторые другие

**Comment by Alastor029711** [comment]
Да, это баг и надо фиксить

**Comment by ark120202** [comment]
It's desired behaviour. That's written in ability description.
