### ISSUE TITLE
фарм крипов во время дуэли

### ISSUE THREAD

**Issue by Alastor029711** [ark120202/angel-arena-black-star#69]
Если ливнуть во время дуэли(живым и тебя убьют) и ты возвращаешься в игру, то во время дуэли персонаж кто умер, когда ливнул сможет идти фармить крипов, по завершению дуэли, он окажеться на фонтане

**Comment by ark120202** [comment]
Need to confirm if it's still an issue after 30592f5fabb497d3defa3cffe9529dbea5a62608.
/cc @ONESpell123
