### ISSUE TITLE
Cherub is broken? 

### ISSUE THREAD

**Issue by masfree** [ark120202/angel-arena-black-star#83]
Hello, now there are big problems with churub, it does not work with ultimate (pots do not plant flowers) and overfilling does not work at all only glows.
Please tell me how to play or fix the character.
Thank you.

Привет, сейчас есть большие проблемы с чурубом у него не работает ульта ( в горшочки не посадить цветы) и перезалив вообще не работает только светится.
Пожалуйста ответьте как им играть или почините персонажа. 
Спасибо.

**Comment by MurzikViskas** [comment]
Just use tab, and u can use ultimate

**Comment by masfree** [comment]
@ark120202 последние обновления чурубу сломали.
Неправильно привязана смена хит поинтов у цветов и бомб.
Я так понимаю у них при битве на арене должен быть 1 хп но привязали и к арене и к смертям из-за этого переключение срабатывает после этих событий в итоге на арене ходят чурубы с 5к хп цветами.
И вообще это очень странное решение для персонажа средней силы делающее его практически бесполезным...

**Comment by ark120202** [comment]
Не понимаю о чем ты. И у цветов, и у спор, хп всегда одно и не должно зависить от чего-то внешнего.
https://github.com/ark120202/angel-arena-black-star/blob/41bd2a7e8179b30df2cce82ec6af528f63563fa8/game/scripts/vscripts/heroes/hero_cherub/flower_garden.lua#L20-L27
